### PR TITLE
Mdi Icon Set Bug Fixed

### PR DESCRIPTION
**Pull request by BNohut**
Solved!

### CODE REVIEW

**Comment by CdTgr** [comment]
@BNohut thank you for your contribution. :)

**Comment by CdTgr** [comment]
@BNohut I rebased it, but then found out that the scoped will affect the styling.

if the scoped attribute is added then the styles on `q-field__control` will no longer work.

**Comment by CdTgr** [comment]
@BNohut I have updated it on a commit and linked to this PR. Btw nice work 😉

**Comment by CdTgr** [comment]
@BNohut Released a new version [v1.1.9](https://www.npmjs.com/package/vue3-q-tel-input/v/1.1.9) with these changes.

**Comment by BNohut** [comment]
Your input plugin is also good and useful. Thank you for considering my PR. 👊

**Pull request merged**
